import os
import pandas as pd

# =============================================================================
# Script purpose
# =============================================================================
# This script aggregates the per-class "*_seg_analysis.xlsx" files generated by
# the mask-checking script and produces two output workbooks:
#   1. A simplified summary workbook with counts/statistics.
#   2. A tracking workbook separating clean files from files with first/last
#      slice labels or edge-touch findings.
# =============================================================================

# =============================================================================
# USER-EDITABLE SETTINGS
# =============================================================================
# USER INPUT REQUIRED:
# Directory containing the per-class "*_seg_analysis.xlsx" files.
seg_analysis_dir = "/path/to/seg_analysis_directory"

# Output workbook paths. These are written into seg_analysis_dir by default.
summary_excel_path = os.path.join(seg_analysis_dir, "AccRejRew_Summary_Simplified.xlsx")
tracking_excel_path = os.path.join(seg_analysis_dir, "AccRejRew_Clean_File_Tracking.xlsx")
os.makedirs(os.path.dirname(summary_excel_path), exist_ok=True)
os.makedirs(os.path.dirname(tracking_excel_path), exist_ok=True)

# =============================================================================
# Excel writer helper
# =============================================================================
def _write_bold_excel(df: pd.DataFrame, writer, sheet_name: str, startrow=0):
    # Write a dataframe and format the header row in bold.
    df.to_excel(writer, index=False, sheet_name=sheet_name, startrow=startrow)
    workbook  = writer.book
    worksheet = writer.sheets[sheet_name]
    header_fmt = workbook.add_format({'bold': True})
    for col_idx, col_name in enumerate(df.columns):
        worksheet.write(startrow, col_idx, col_name, header_fmt)

# =============================================================================
# Load all segmentation-analysis workbooks
# =============================================================================
all_dfs = []
for fname in os.listdir(seg_analysis_dir):
    if fname.endswith("_seg_analysis.xlsx"):
        df = pd.read_excel(os.path.join(seg_analysis_dir, fname))
        df["Source_File"] = fname
        all_dfs.append(df)

if not all_dfs:
    raise ValueError("No seg_analysis spreadsheets found in directory.")

# Concatenate all source files into one dataframe for summary calculations.
df_all = pd.concat(all_dfs, ignore_index=True)
total_unique = df_all["Names"].nunique()
total_rows = pd.DataFrame({"Total_Unique_Filenames": [total_unique]})

# =============================================================================
# Summary-sheet helper
# =============================================================================
def create_abv_sheet(df, threshold=0):
    # Build the Abv0 sheet by listing files with first/last slice voxel counts
    # above the given threshold.
    df = df.copy()
    records = []
    cols = ["FirstSlice_Label1_Voxels", "FirstSlice_Label2_Voxels",
            "LastSlice_Label1_Voxels", "LastSlice_Label2_Voxels"]
    for _, row in df.iterrows():
        over_thresh_cols = [col for col in cols if row[col] > threshold]
        if over_thresh_cols:
            records.append({
                "Names": row["Names"],
                "Columns": ", ".join(over_thresh_cols),
                "Values": ", ".join(str(row[col]) for col in over_thresh_cols),
                "Str_Label": row["Str_Labels"]
            })
    df_records = pd.DataFrame(records)
    df_grouped = df_records.groupby("Names", as_index=False).agg({
        "Columns": lambda x: ", ".join(sorted(set(", ".join(x).split(", ")))) ,
        "Values": lambda x: ", ".join(str(v) for v in x),
        "Str_Label": lambda x: ", ".join(sorted(set(x)))
    })
    return df_grouped

abv0_df  = create_abv_sheet(df_all, 0)

# =============================================================================
# Statistics helpers
# =============================================================================
def generate_stats_table(df_grouped, total_count, filename_col="Names"):
    # Return count plus percentages relative to the current denominator and the
    # global total. Percentages are also returned even when only the count is
    # used by the caller.
    count_unique = df_grouped[filename_col].nunique()
    pct_class = count_unique / total_count if total_count > 0 else 0
    pct_global = count_unique / total_unique if total_unique > 0 else 0
    return count_unique, pct_class, pct_global


def generate_detailed_stats(df, threshold=0, denom_count=None):
    # Generate two summary tables for a subset:
    #   table1 -> count / mean / median
    #   table2 -> percentages
    df = df.copy()
    denom = df["Names"].nunique() if denom_count is None else denom_count

    # Table 1: Avg/Median/Count for first/last-slice voxel findings.
    stats_rows = []
    cols = ["FirstSlice_Label1_Voxels", "FirstSlice_Label2_Voxels",
            "LastSlice_Label1_Voxels", "LastSlice_Label2_Voxels"]

    for col in cols:
        filtered = df[df[col] > threshold]
        avg_val = filtered[col].mean() if not filtered.empty else 0
        med_val = filtered[col].median() if not filtered.empty else 0
        count, _, _ = generate_stats_table(filtered, denom, filename_col="Names")
        stats_rows.append({"Metric": col, "Avg": avg_val, "Median": med_val, "Count": count})

    # Cases where both label 1 and label 2 appear on the first or last slice.
    df["Both_First"] = (df["FirstSlice_Label1_Voxels"] > 0) & (df["FirstSlice_Label2_Voxels"] > 0)
    df["Both_Last"]  = (df["LastSlice_Label1_Voxels"] > 0) & (df["LastSlice_Label2_Voxels"] > 0)

    for name, col in [("Both Labels - First Slice", "Both_First"), ("Both Labels - Last Slice", "Both_Last")]:
        count, _, _ = generate_stats_table(df[df[col]], denom, filename_col="Names")
        stats_rows.append({"Metric": name, "Avg": "", "Median": "", "Count": count})

    # Any label on either end slice.
    any_label_mask = df[["FirstSlice_Label1_Voxels","FirstSlice_Label2_Voxels",
                         "LastSlice_Label1_Voxels","LastSlice_Label2_Voxels"]].sum(axis=1) > 0
    count, _, _ = generate_stats_table(df[any_label_mask], denom, filename_col="Names")
    stats_rows.append({"Metric": "Any Label - First or Last Slice", "Avg": "", "Median": "", "Count": count})

    # XY edge touch detection.
    df["XY_Touch"] = df["Sides_Touched"].apply(lambda s: any(x in str(s) for x in ["x0","xN","y0","yN"]))
    count, _, _ = generate_stats_table(df[df["XY_Touch"]], denom, filename_col="Names")
    stats_rows.append({"Metric": "X or Y edge", "Avg": "", "Median": "", "Count": count})

    # XYZ edge touch detection.
    df["XYZ_Touch"] = df["Sides_Touched"].apply(lambda s: any(x in str(s) for x in ["x0","xN","y0","yN","z0","zN"]))
    count, _, _ = generate_stats_table(df[df["XYZ_Touch"]], denom, filename_col="Names")
    stats_rows.append({"Metric": "X or Y or Z edge", "Avg": "", "Median": "", "Count": count})

    table1 = pd.DataFrame(stats_rows)

    # Table 2: percentages in decimal form.
    pct_rows = []
    for row in stats_rows:
        count_row = row["Count"]
        pct_class = count_row / denom if denom > 0 else 0
        pct_global = count_row / total_unique if total_unique > 0 else 0
        pct_rows.append({"Metric": row["Metric"], "% (per class)": pct_class, "% (Global)": pct_global})
    table2 = pd.DataFrame(pct_rows)

    return table1, table2

# =============================================================================
# Build per-class and total summary tables
# =============================================================================
labels = ["Accept", "Reject", "Rework"]
abv0_stats_tables = {}

for lbl in labels + ["Total"]:
    if lbl == "Total":
        df_subset = df_all
        denom_count = total_unique
    else:
        df_subset = df_all[df_all["Str_Labels"].str.contains(lbl)]
        denom_count = df_subset["Names"].nunique()
    abv0_stats_tables[lbl] = generate_detailed_stats(df_subset, threshold=0, denom_count=denom_count)

# =============================================================================
# Build All_Files_Info sheet
# =============================================================================
df_all_info = df_all.copy()
all_records = []
for _, row in df_all_info.iterrows():
    types_set = set()
    labels_set = set()
    for label_num in [1,2]:
        for suffix in ["FirstSlice", "LastSlice"]:
            col = f"{suffix}_Label{label_num}_Voxels"
            if row[col] > 0:
                types_set.add(f"{suffix}_Label")
                labels_set.add(label_num)
    sides = str(row["Sides_Touched"])
    if sides.lower() != "nan" and sides != "":
        types_set.add("Edge_Touch")
        labels_set.add("Any")
    all_records.append({
        "Filename": row["Names"],
        "Type": ", ".join(sorted(types_set)),
        "Label": ", ".join(sorted(str(v) for v in labels_set)),
        "Str_Label": row["Str_Labels"]
    })

all_files_info_df = pd.DataFrame(all_records).drop_duplicates(subset=["Filename"])
all_files_info_df = all_files_info_df.groupby("Filename", as_index=False).agg({
    "Type": lambda x: ", ".join(sorted(set(", ".join(x).split(", ")))) ,
    "Label": lambda x: ", ".join(sorted(set(", ".join(x).split(",")))) ,
    "Str_Label": lambda x: ", ".join(sorted(set(x)))
})

# =============================================================================
# Separate clean files from files with findings
# =============================================================================
# Rename for consistency with the source workbooks.
all_files_info_df = all_files_info_df.rename(columns={"Filename": "Names"})

# Columns pulled through from the original concatenated dataframe.
extra_cols = ["Names", "Directories", "Seg_dirs"]

# Clean files have no recorded type/label finding.
clean_df = all_files_info_df[all_files_info_df["Type"] == ""].copy()
clean_df = clean_df.merge(df_all[extra_cols], on="Names", how="left")
clean_df = clean_df.drop(columns=["Type", "Label"]).sort_values("Str_Label")
clean_df = clean_df[["Names", "Directories", "Str_Label", "Seg_dirs"]]

# LabelOrTouch files contain at least one first/last-slice or edge-touch finding.
label_or_touch_df = all_files_info_df[all_files_info_df["Type"] != ""].copy()
label_or_touch_df = label_or_touch_df.merge(df_all[extra_cols], on="Names", how="left")
label_or_touch_df = label_or_touch_df.sort_values("Str_Label")
label_or_touch_df = label_or_touch_df[["Names", "Directories", "Type", "Label", "Str_Label", "Seg_dirs"]]

# =============================================================================
# Write summary workbook
# =============================================================================
with pd.ExcelWriter(summary_excel_path, engine="xlsxwriter") as writer:
    _write_bold_excel(abv0_df, writer, "Abv0")
    _write_bold_excel(total_rows, writer, "TotalRows")
    for lbl, (table1, table2) in abv0_stats_tables.items():
        # Write counts table first, then percentages table below it.
        _write_bold_excel(table1, writer, lbl, startrow=0)
        _write_bold_excel(table2, writer, lbl, startrow=len(table1)+2)
    _write_bold_excel(all_files_info_df, writer, "All_Files_Info")

# =============================================================================
# Write tracking workbook
# =============================================================================
with pd.ExcelWriter(tracking_excel_path, engine="xlsxwriter") as writer:
    _write_bold_excel(clean_df, writer, "Clean_Files")
    _write_bold_excel(label_or_touch_df, writer, "LabelOrTouch_Files")
