Backbone1:
  modelclass: DenseNetFeatures
  inputs:
    model_name: DenseNet121 # supports resnet18, resnet34, resnet50, resnet101, resnet152, densenet121
    in_channels: 1
    flatten: true
    #pretrained_path:
    
Backbone2: 
  modelclass: DenseNetFeatures
  inputs:
    model_name: DenseNet121 # supports resnet18, resnet34, resnet50, resnet101, resnet152, densenet121
    in_channels: 1
    flatten: true
    #pretrained_path:
    
Backbone3:
  modelclass: DenseNetFeatures
  inputs:
    model_name: DenseNet121 # supports resnet18, resnet34, resnet50, resnet101, resnet152, densenet121
    in_channels: 1
    flatten: true
    #pretrained_path:
