# -*- coding: utf-8 -*-
"""
Standard Experimental Set Creator
- Reads QC-tracking sheets generated by GenerateSimplifiedCoverageSummary.py
- Uses all technically eligible cases by default; coverage findings remain metadata
- Supports optional all-splits or historical test-only coverage filtering
- Preserves the existing balanced-split modes and output naming conventions
- Keeps all scans from the same patient within one final split
- Fuzzy matches missing files (>=95%)
- Copies images + segmentations into split/class folders
- Saves train/val/test Excel logs
"""

import os
import shutil

import pandas as pd
from rapidfuzz import fuzz, process
from sklearn.model_selection import StratifiedGroupKFold
from tqdm import tqdm

# =============================================================================
# USER-EDITABLE SETTINGS
# =============================================================================
# USER INPUT REQUIRED:
# Path to the tracking workbook generated by GenerateSimplifiedCoverageSummary.py.
# The workbook is expected to contain sheets named "Clean_Files" and
# "LabelOrTouch_Files".
main_excel = "/path/to/AccRejRew_Clean_File_Tracking.xlsx"

# USER INPUT REQUIRED:
# Root directory containing image files organized by class subfolder:
#   images_root/
#       Accept/
#       Reject/
#       Rework/
# Segmentations may also be resolved relative to these folders when needed.
images_root = "/path/to/images_and_segmentations_root"

# USER INPUT REQUIRED:
# Parent directory where the curated standardized dataset will be created.
output_root = "/path/to/output_root"

# The script creates this dataset folder inside output_root.
output_set = os.path.join(output_root, "Standardized_Experimental_Set")

# Number of samples per class used in fully balanced mode. When
# BALANCE_VAL_TEST_ONLY = True, this value determines the per-class sizing of
# validation and test subsets (0.2 * n_per_class for each split).
n_per_class = 1000
random_seed = 42

# Mode switch retained from the original workflow:
# - False: select exactly n_per_class rows per class, then target a patient-
#          disjoint 60/20/20 train/val/test split.
# - True:  select balanced validation and test rows, with the remaining eligible
#          rows placed in training after removing all held-out patients.
BALANCE_VAL_TEST_ONLY = True

# Coverage filtering policy:
# - "none" (recommended): use both Clean_Files and LabelOrTouch_Files when
#   creating train, validation, and test. CheckMask findings remain metadata.
# - "all_splits": use only Clean_Files for all three splits.
# - "historical_test_only": use Clean_Files for the test cohort, but use the
#   full eligible cohort for train/validation. This is retained only for
#   historical reproducibility and requires BALANCE_VAL_TEST_ONLY = True.
COVERAGE_FILTER_MODE = "none"

# Preferred: specify a deidentified patient/group column that is already present
# in the tracking workbook (for example, "Patient_ID"). If None, the first
# underscore-delimited token in Names is used as the patient group.
PATIENT_ID_COLUMN = None
PATIENT_ID_NAME_SEPARATOR = "_"

# Internal helper column. It is removed before logs are saved.
_GROUP_COLUMN = "__PatientGroup"

# =============================================================================
# Helpers: source preparation and patient grouping
# =============================================================================
def _normalize_names(df):
    """Normalize image filenames to the nnUNet-style image suffix."""
    out = df.copy()
    out["Names"] = out["Names"].astype(str).apply(
        lambda x: x if x.endswith("_0000.nii.gz") else x.replace(".nii.gz", "_0000.nii.gz")
    )
    return out


def _add_patient_groups(df, source_name):
    """Return a copy with a temporary patient/group identifier column."""
    out = df.copy()

    if PATIENT_ID_COLUMN is not None:
        if PATIENT_ID_COLUMN not in out.columns:
            raise KeyError(
                f"{source_name} does not contain PATIENT_ID_COLUMN="
                f"{PATIENT_ID_COLUMN!r}."
            )
        groups = out[PATIENT_ID_COLUMN]
    else:
        if "Names" not in out.columns:
            raise KeyError(
                f"{source_name} must contain 'Names' when PATIENT_ID_COLUMN is None."
            )
        groups = (
            out["Names"]
            .astype(str)
            .str.split(PATIENT_ID_NAME_SEPARATOR, n=1)
            .str[0]
        )

    groups = groups.astype(str).str.strip()
    invalid = groups.eq("") | groups.str.lower().eq("nan")
    if invalid.any():
        bad_rows = invalid[invalid].index[:10].tolist()
        raise ValueError(
            f"Unable to determine patient group for rows {bad_rows} in {source_name}."
        )

    out[_GROUP_COLUMN] = groups
    return out


def _load_tracking_sheets():
    """Load both QC tracking sheets while preserving their existing columns."""
    workbook = pd.read_excel(main_excel, sheet_name=None)

    required = {"Clean_Files", "LabelOrTouch_Files"}
    missing = required - set(workbook)
    if missing:
        raise KeyError(
            f"Tracking workbook is missing required sheet(s): {sorted(missing)}"
        )

    clean = workbook["Clean_Files"].copy()
    flagged = workbook["LabelOrTouch_Files"].copy()

    # Preserve the QC category as metadata. Older tracking workbooks that do not
    # yet contain Coverage_Status remain supported.
    if "Coverage_Status" not in clean.columns:
        clean["Coverage_Status"] = "No_Coverage_Flag"
    else:
        clean["Coverage_Status"] = clean["Coverage_Status"].fillna("No_Coverage_Flag")

    if "Coverage_Status" not in flagged.columns:
        flagged["Coverage_Status"] = "Coverage_Flag"
    else:
        flagged["Coverage_Status"] = flagged["Coverage_Status"].fillna("Coverage_Flag")

    classes = ["Accept", "Reject", "Rework"]
    clean = clean[clean["Str_Label"].isin(classes)].copy()
    flagged = flagged[flagged["Str_Label"].isin(classes)].copy()

    clean = _normalize_names(clean)
    flagged = _normalize_names(flagged)

    clean = _add_patient_groups(clean, "Clean_Files")
    flagged = _add_patient_groups(flagged, "LabelOrTouch_Files")

    # The two sheets should be mutually exclusive. Drop duplicate Names only as
    # a safeguard against an accidentally duplicated tracking entry.
    full = pd.concat([clean, flagged], ignore_index=True, sort=False)
    full = full.drop_duplicates(subset=["Names"], keep="first").reset_index(drop=True)

    return clean.reset_index(drop=True), flagged.reset_index(drop=True), full


def _grouped_holdout_split(df, holdout_fraction, seed):
    """
    Split a dataframe into development and holdout portions while keeping each
    patient wholly within one side. The candidate fold closest to the requested
    row fraction and class distribution is selected deterministically.
    """
    if not 0 < holdout_fraction < 1:
        raise ValueError("holdout_fraction must be between 0 and 1.")

    n_splits = int(round(1.0 / holdout_fraction))
    if n_splits < 2:
        raise ValueError("Grouped splitting requires at least two folds.")

    n_groups = df[_GROUP_COLUMN].nunique()
    if n_groups < n_splits:
        raise ValueError(
            f"Need at least {n_splits} unique patients/groups, found {n_groups}."
        )

    splitter = StratifiedGroupKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=seed,
    )

    target_props = df["Str_Label"].value_counts(normalize=True)
    best = None

    for develop_idx, holdout_idx in splitter.split(
        X=df,
        y=df["Str_Label"],
        groups=df[_GROUP_COLUMN],
    ):
        holdout = df.iloc[holdout_idx]
        actual_fraction = len(holdout) / len(df)
        holdout_props = holdout["Str_Label"].value_counts(normalize=True)

        class_deviation = sum(
            abs(holdout_props.get(cls, 0.0) - target_props.get(cls, 0.0))
            for cls in target_props.index
        )
        score = abs(actual_fraction - holdout_fraction) + class_deviation

        if best is None or score < best[0]:
            best = (score, develop_idx, holdout_idx)

    if best is None:
        raise RuntimeError("Unable to create a grouped holdout split.")

    _, develop_idx, holdout_idx = best
    develop_df = df.iloc[develop_idx].copy().reset_index(drop=True)
    holdout_df = df.iloc[holdout_idx].copy().reset_index(drop=True)
    return develop_df, holdout_df


def _sample_per_class(df, n_per_class_target, split_name):
    """Preserve the original fixed-count per-class sampling behavior."""
    blocks = []
    for cls in classes:
        cls_subset = df[df["Str_Label"] == cls]
        if len(cls_subset) < n_per_class_target:
            raise ValueError(
                f"Class '{cls}' has {len(cls_subset)} samples, need "
                f"{n_per_class_target} for {split_name}."
            )
        blocks.append(
            cls_subset.sample(
                n=n_per_class_target,
                random_state=random_seed,
            )
        )
    return pd.concat(blocks).reset_index(drop=True)


def _require_all_classes(df, split_name):
    missing = set(classes) - set(df["Str_Label"].dropna().unique())
    if missing:
        raise RuntimeError(
            f"Patient grouping produced no {sorted(missing)} rows in {split_name}. "
            "Try a different random_seed or n_per_class."
        )


def _assert_patient_disjoint(train_df, val_df, test_df):
    """Fail immediately if a patient appears in more than one final split."""
    train_groups = set(train_df[_GROUP_COLUMN])
    val_groups = set(val_df[_GROUP_COLUMN])
    test_groups = set(test_df[_GROUP_COLUMN])

    overlaps = {
        "train/val": train_groups & val_groups,
        "train/test": train_groups & test_groups,
        "val/test": val_groups & test_groups,
    }
    overlaps = {name: values for name, values in overlaps.items() if values}

    if overlaps:
        summary = {name: len(values) for name, values in overlaps.items()}
        raise RuntimeError(f"Patient leakage detected: {summary}")

    print("\nPatient-disjoint split check passed:")
    print(f"  Train patients: {len(train_groups)}")
    print(f"  Val patients:   {len(val_groups)}")
    print(f"  Test patients:  {len(test_groups)}")


# =============================================================================
# Load source data and select coverage policy
# =============================================================================
classes = ["Accept", "Reject", "Rework"]
df_clean, df_flagged, df_full = _load_tracking_sheets()

valid_filter_modes = {"none", "all_splits", "historical_test_only"}
if COVERAGE_FILTER_MODE not in valid_filter_modes:
    raise ValueError(
        f"COVERAGE_FILTER_MODE must be one of {sorted(valid_filter_modes)}, "
        f"found {COVERAGE_FILTER_MODE!r}."
    )

if COVERAGE_FILTER_MODE == "none":
    split_source = df_full.copy()
    print("Coverage filtering: none (using Clean_Files + LabelOrTouch_Files).")
elif COVERAGE_FILTER_MODE == "all_splits":
    split_source = df_clean.copy()
    print("Coverage filtering: Clean_Files only for all splits.")
else:
    if not BALANCE_VAL_TEST_ONLY:
        raise ValueError(
            "COVERAGE_FILTER_MODE='historical_test_only' requires "
            "BALANCE_VAL_TEST_ONLY=True."
        )
    split_source = df_full.copy()
    print(
        "[WARNING] historical_test_only is retained for historical "
        "reproducibility. New from-scratch experiments should use "
        "COVERAGE_FILTER_MODE='none'."
    )

print("\nEligible rows before splitting:")
print(f"  Clean_Files:        {len(df_clean)}")
print(f"  LabelOrTouch_Files: {len(df_flagged)}")
print(f"  Full eligible:      {len(df_full)}")

# =============================================================================
# Build patient-disjoint train/val/test splits
# =============================================================================
if not BALANCE_VAL_TEST_ONLY:
    # Mode 1: preserve the original row-selection step, then make the selected
    # cohort patient-disjoint with an approximately stratified 60/20/20 split.
    selected_df = _sample_per_class(
        split_source,
        n_per_class_target=n_per_class,
        split_name="fully balanced cohort",
    )

    trainval_df, test_df = _grouped_holdout_split(
        selected_df,
        holdout_fraction=0.20,
        seed=random_seed,
    )
    train_df, val_df = _grouped_holdout_split(
        trainval_df,
        holdout_fraction=0.25,
        seed=random_seed + 1,
    )

else:
    n_valtest_per_class = int(0.2 * n_per_class)

    if COVERAGE_FILTER_MODE == "historical_test_only":
        # Historical option: construct the test cohort from Clean_Files, then
        # construct validation from all remaining eligible patients.
        test_df = _sample_per_class(
            df_clean,
            n_per_class_target=n_valtest_per_class,
            split_name="test",
        )
        test_groups = set(test_df[_GROUP_COLUMN])

        remaining_after_test = df_full[
            ~df_full[_GROUP_COLUMN].isin(test_groups)
        ].copy()

        val_df = _sample_per_class(
            remaining_after_test,
            n_per_class_target=n_valtest_per_class,
            split_name="validation",
        )
        val_groups = set(val_df[_GROUP_COLUMN])

        # Preserve the original fixed held-out row counts. Additional scans from
        # held-out patients are excluded from training rather than automatically
        # added to validation/test.
        train_df = remaining_after_test[
            ~remaining_after_test[_GROUP_COLUMN].isin(val_groups)
        ].copy().reset_index(drop=True)

    else:
        # Mode 2: preserve the original combined balanced val/test row sample,
        # then assign the sampled rows by patient group.
        val_test_df = _sample_per_class(
            split_source,
            n_per_class_target=2 * n_valtest_per_class,
            split_name="combined validation/test cohort",
        )

        _, sampled_test_df = _grouped_holdout_split(
            val_test_df,
            holdout_fraction=0.50,
            seed=random_seed,
        )
        test_groups = set(sampled_test_df[_GROUP_COLUMN])

        test_df = val_test_df[
            val_test_df[_GROUP_COLUMN].isin(test_groups)
        ].copy().reset_index(drop=True)
        val_df = val_test_df[
            ~val_test_df[_GROUP_COLUMN].isin(test_groups)
        ].copy().reset_index(drop=True)

        heldout_groups = set(val_df[_GROUP_COLUMN]) | set(test_df[_GROUP_COLUMN])
        sampled_names = set(val_test_df["Names"])

        # Begin with the original remaining-row concept, then remove every other
        # scan belonging to a held-out patient to enforce patient disjointness.
        remaining_df = split_source[
            ~split_source["Names"].isin(sampled_names)
        ].copy()
        train_df = remaining_df[
            ~remaining_df[_GROUP_COLUMN].isin(heldout_groups)
        ].copy().reset_index(drop=True)

for split_name, split_df in {
    "train": train_df,
    "validation": val_df,
    "test": test_df,
}.items():
    _require_all_classes(split_df, split_name)

_assert_patient_disjoint(train_df, val_df, test_df)

print("\nDataset composition:")
print(f"  Train: {len(train_df)}")
print(f"  Val:   {len(val_df)}")
print(f"  Test:  {len(test_df)}")

print("\nClass counts:")
for split_name, split_df in {
    "Train": train_df,
    "Val": val_df,
    "Test": test_df,
}.items():
    print(f"  {split_name}: {split_df['Str_Label'].value_counts().to_dict()}")

# =============================================================================
# Add numeric labels
# =============================================================================
label_map = {"Accept": 0, "Reject": 1, "Rework": 2}
for df_tmp in [train_df, val_df, test_df]:
    df_tmp["Label"] = df_tmp["Str_Label"].map(label_map)

# =============================================================================
# Create output folder structure
# =============================================================================
splits = ["train", "val", "test"]

for split in splits:
    for cls in classes:
        os.makedirs(os.path.join(output_set, split, cls), exist_ok=True)

# =============================================================================
# File copy helpers
# =============================================================================
def fuzzy_find_missing(src_path, search_dir):
    """
    If file missing, fuzzy match inside search_dir.
    Returns best guess path or None.
    """
    files = os.listdir(search_dir)
    best = process.extractOne(
        os.path.basename(src_path), files, scorer=fuzz.partial_ratio
    )
    if best and best[1] >= 95:
        print(f"Fuzzy matched: {os.path.basename(src_path)} -> {best[0]}")
        return os.path.join(search_dir, best[0])
    return None


def safe_copy(src, dst_dir):
    # Copy a file if present; otherwise attempt fuzzy recovery within the same
    # parent directory. Returns the copied output path or None.
    if os.path.exists(src):
        shutil.copy2(src, dst_dir)
        return os.path.join(dst_dir, os.path.basename(src))

    parent_dir = os.path.dirname(src)
    if os.path.isdir(parent_dir):
        match = fuzzy_find_missing(src, parent_dir)
        if match:
            shutil.copy2(match, dst_dir)
            return os.path.join(dst_dir, os.path.basename(match))

    print(f"Missing file (no copy): {src}")
    return None


all_splits = {"train": train_df, "val": val_df, "test": test_df}

# =============================================================================
# Copy images and segmentations
# =============================================================================
print("\nCopying images + segmentations...")

for split_name, df_split in all_splits.items():

    out_dirs1, out_dirs2, out_seg_dirs = [], [], []

    for _, row in tqdm(df_split.iterrows(), total=len(df_split), desc=f"Copying {split_name}"):

        fname = row["Names"]
        cls = row["Str_Label"]

        seg_value = row.get("Seg_dirs", "")
        seg_src = "" if pd.isna(seg_value) else str(seg_value).strip()
        img_src = os.path.join(images_root, cls, fname)

        dst_folder = os.path.join(output_set, split_name, cls)

        # Copy the image file into the destination split/class folder.
        copied_img = safe_copy(img_src, dst_folder)

        # Copy the segmentation file. If the absolute path in Seg_dirs is not
        # valid, fall back to resolving the basename relative to images_root.
        seg_name = os.path.basename(seg_src) if seg_src else ""
        seg_src_norm = (
            seg_src
            if seg_src and os.path.exists(seg_src)
            else os.path.join(images_root, cls, seg_name)
        )
        copied_seg = safe_copy(seg_src_norm, dst_folder) if seg_name else None

        # Preserve the existing output column names so downstream scripts remain
        # compatible with prior datasets.
        out_dirs1.append(copied_img)
        out_dirs2.append(copied_img)
        out_seg_dirs.append(copied_seg)

    df_split["Directories1"] = out_dirs1
    df_split["Directories2"] = out_dirs2
    df_split["Seg_Dirs"] = out_seg_dirs

# =============================================================================
# Remove internal grouping helper and save split logs
# =============================================================================
for df_tmp in [train_df, val_df, test_df]:
    df_tmp.drop(columns=[_GROUP_COLUMN], errors="ignore", inplace=True)

train_df.to_excel(
    os.path.join(output_set, "AccRejRew_StandardExpSet_train_log.xlsx"),
    index=False,
)
val_df.to_excel(
    os.path.join(output_set, "AccRejRew_StandardExpSet_val_log.xlsx"),
    index=False,
)
test_df.to_excel(
    os.path.join(output_set, "AccRejRew_StandardExpSet_test_log.xlsx"),
    index=False,
)

print("\nStandard Experimental Set complete!")
print(f"Train samples: {len(train_df)}")
print(f"Val samples:   {len(val_df)}")
print(f"Test samples:  {len(test_df)}")
print(f"Output directory: {output_set}")
